module.exports = {
  password: null,
  account: null,
  mnemonic: null,
  refresh_network: null,
  refresh_wallet_list: null,
  refresh_current: null,
  importMnemonic: null,
  dob: null,
  sudt: null,
  xudt: null,
  cluster: null,
  stealthex_token: null,
  exchangeList: [],
  currentToken: { symbol: "usdt", network: "trx" },
};
