name: CI Build | Dev Branch

on:
  push:
    branches: [ dev ]

jobs:     
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      SENTRY_AUTH_TOKEN: ${{ SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Build
        run: |
          npm install
          npm run build
        env:
          CI: false
